# Development Environment Configuration for NeuronMap
# ==================================================

# Inherit from base environment.yaml and override specific settings
environment:
  # Development-specific settings
  environment: "development"
  
  # Logging Configuration (verbose for development)
  log_level: "DEBUG"
  enable_debugging: true
  log_to_file: true
  log_file_path: "logs/neuronmap_dev.log"
  log_rotation: true
  max_log_size_mb: 50
  backup_count: 3
  
  # Performance Settings (conservative for dev)
  max_workers: 2
  timeout_seconds: 180
  memory_limit_gb: 16
  cpu_limit_percent: 60
  
  # System Monitoring (frequent for development)
  monitoring:
    enable_system_monitoring: true
    monitor_gpu_usage: true
    monitor_memory_usage: true
    monitor_cpu_usage: true
    monitoring_interval_seconds: 5
    alert_threshold_memory_percent: 80
    alert_threshold_gpu_memory_percent: 85
  
  # Error Handling (permissive for development)
  error_handling:
    enable_error_recovery: true
    max_retry_attempts: 5
    retry_delay_seconds: 2
    enable_graceful_shutdown: true
    error_reporting: true
    fail_fast_on_validation_errors: false
  
  # Security Settings (relaxed for development)
  security:
    validate_inputs: true
    sanitize_file_paths: true
    max_file_size_mb: 500
    allowed_file_extensions: [".txt", ".json", ".yaml", ".csv", ".h5", ".hdf5", ".py", ".md"]
    enable_model_verification: false
  
  # Cache Configuration (aggressive caching for dev)
  cache:
    enable_caching: true
    cache_directory: "cache/dev"
    max_cache_size_gb: 5
    cache_ttl_hours: 24
    auto_cleanup: true
  
  # Development-specific features
  development:
    enable_hot_reload: true
    auto_save_interval_seconds: 30
    enable_profiling: true
    mock_external_services: false
    enable_experimental_features: true
